version: '3'

services:
  mongodb:
    image: mongo:4
    env_file: .env
    ports:
      - "27017-27019:27017-27019"
  mongodb_web:
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
  redis:
    image: redis:5
    env_file: .env
    ports:
      - "6379:6379"
  bull_board:
    image: deadly0/bull-board
    depends_on:
      - redis
    ports:
      - "8091:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USE_TLS: 'false'
